#Запуск приложения
run-dist:
	./build/install/app/bin/app src/main/java/hexlet/code/file1.json src/main/java/hexlet/code/file2.json
	./build/install/app/bin/app src/main/java/hexlet/code/file1.yml src/main/java/hexlet/code/file2.yml

build:
	./gradlew build


.PHONY: build